imager:
  build: imager/
  ports:
    - "8001:8000"
  volumes:
    - ./imager/:/imager/
comparer:
  build: comparer/
  links:
    - postgres
    - imager
  volumes:
    - ./comparer/:/comparer/
  environment:
    - DATABASE_URL=postgres://postgres:mysecretpassword@postgres/postgres
frontend:
  build: frontend/
  volumes:
    - ./frontend/:/frontend/
  ports:
    - "8000:8000"
  links:
    - postgres
  environment:
    - DATABASE_URL=postgres://postgres:mysecretpassword@postgres/postgres
postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=mysecretpassword
