# Scan this file for changes every 30 seconds
refresh_rate = 30

# An appender named "stdout" that writes to stdout
[appenders.stdout]
kind = "console"

[root]
level = "debug"
appenders = ["stdout"]

[loggers."hyper"]
level = "info"

[loggers."mime"]
level = "info"
